enum Behavior {
  DO_NOTHING,
  QUIT_GAME,
  MOVE_UP,
  MOVE_DOWN,
  MOVE_LEFT,
  MOVE_RIGHT,
  MOVE_UPLEFT,
  MOVE_DOWNLEFT,
  MOVE_UPRIGHT,
  MOVE_DOWNRIGHT
};

const static std::map<const std::string, const Behavior> behavior_map = {
  {"DO_NOTHING", DO_NOTHING},
  {"QUIT_GAME", QUIT_GAME},
  {"MOVE_UP", MOVE_UP},
  {"MOVE_DOWN", MOVE_DOWN},
  {"MOVE_LEFT", MOVE_LEFT},
  {"MOVE_RIGHT", MOVE_RIGHT},
  {"MOVE_UPLEFT", MOVE_UPLEFT},
  {"MOVE_DOWNLEFT", MOVE_DOWNLEFT},
  {"MOVE_UPRIGHT", MOVE_UPRIGHT},
  {"MOVE_DOWNRIGHT", MOVE_DOWNRIGHT},
};
